/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MarketGapsRouteImport } from './routes/market-gaps'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WizardStep7RouteImport } from './routes/wizard.step-7'
import { Route as WizardStep6RouteImport } from './routes/wizard.step-6'
import { Route as WizardStep5RouteImport } from './routes/wizard.step-5'
import { Route as WizardStep4RouteImport } from './routes/wizard.step-4'
import { Route as WizardStep3RouteImport } from './routes/wizard.step-3'
import { Route as WizardStep2RouteImport } from './routes/wizard.step-2'
import { Route as WizardStep1RouteImport } from './routes/wizard.step-1'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketGapsRoute = MarketGapsRouteImport.update({
  id: '/market-gaps',
  path: '/market-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardStep7Route = WizardStep7RouteImport.update({
  id: '/step-7',
  path: '/step-7',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep6Route = WizardStep6RouteImport.update({
  id: '/step-6',
  path: '/step-6',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep5Route = WizardStep5RouteImport.update({
  id: '/step-5',
  path: '/step-5',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep4Route = WizardStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep3Route = WizardStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep2Route = WizardStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => WizardRoute,
} as any)
const WizardStep1Route = WizardStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => WizardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autopilot': typeof AutopilotRoute
  '/market-gaps': typeof MarketGapsRoute
  '/report': typeof ReportRoute
  '/startups': typeof StartupsRoute
  '/wizard': typeof WizardRouteWithChildren
  '/wizard/step-1': typeof WizardStep1Route
  '/wizard/step-2': typeof WizardStep2Route
  '/wizard/step-3': typeof WizardStep3Route
  '/wizard/step-4': typeof WizardStep4Route
  '/wizard/step-5': typeof WizardStep5Route
  '/wizard/step-6': typeof WizardStep6Route
  '/wizard/step-7': typeof WizardStep7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autopilot': typeof AutopilotRoute
  '/market-gaps': typeof MarketGapsRoute
  '/report': typeof ReportRoute
  '/startups': typeof StartupsRoute
  '/wizard': typeof WizardRouteWithChildren
  '/wizard/step-1': typeof WizardStep1Route
  '/wizard/step-2': typeof WizardStep2Route
  '/wizard/step-3': typeof WizardStep3Route
  '/wizard/step-4': typeof WizardStep4Route
  '/wizard/step-5': typeof WizardStep5Route
  '/wizard/step-6': typeof WizardStep6Route
  '/wizard/step-7': typeof WizardStep7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autopilot': typeof AutopilotRoute
  '/market-gaps': typeof MarketGapsRoute
  '/report': typeof ReportRoute
  '/startups': typeof StartupsRoute
  '/wizard': typeof WizardRouteWithChildren
  '/wizard/step-1': typeof WizardStep1Route
  '/wizard/step-2': typeof WizardStep2Route
  '/wizard/step-3': typeof WizardStep3Route
  '/wizard/step-4': typeof WizardStep4Route
  '/wizard/step-5': typeof WizardStep5Route
  '/wizard/step-6': typeof WizardStep6Route
  '/wizard/step-7': typeof WizardStep7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/autopilot'
    | '/market-gaps'
    | '/report'
    | '/startups'
    | '/wizard'
    | '/wizard/step-1'
    | '/wizard/step-2'
    | '/wizard/step-3'
    | '/wizard/step-4'
    | '/wizard/step-5'
    | '/wizard/step-6'
    | '/wizard/step-7'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/autopilot'
    | '/market-gaps'
    | '/report'
    | '/startups'
    | '/wizard'
    | '/wizard/step-1'
    | '/wizard/step-2'
    | '/wizard/step-3'
    | '/wizard/step-4'
    | '/wizard/step-5'
    | '/wizard/step-6'
    | '/wizard/step-7'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/autopilot'
    | '/market-gaps'
    | '/report'
    | '/startups'
    | '/wizard'
    | '/wizard/step-1'
    | '/wizard/step-2'
    | '/wizard/step-3'
    | '/wizard/step-4'
    | '/wizard/step-5'
    | '/wizard/step-6'
    | '/wizard/step-7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AutopilotRoute: typeof AutopilotRoute
  MarketGapsRoute: typeof MarketGapsRoute
  ReportRoute: typeof ReportRoute
  StartupsRoute: typeof StartupsRoute
  WizardRoute: typeof WizardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-gaps': {
      id: '/market-gaps'
      path: '/market-gaps'
      fullPath: '/market-gaps'
      preLoaderRoute: typeof MarketGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/step-7': {
      id: '/wizard/step-7'
      path: '/step-7'
      fullPath: '/wizard/step-7'
      preLoaderRoute: typeof WizardStep7RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-6': {
      id: '/wizard/step-6'
      path: '/step-6'
      fullPath: '/wizard/step-6'
      preLoaderRoute: typeof WizardStep6RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-5': {
      id: '/wizard/step-5'
      path: '/step-5'
      fullPath: '/wizard/step-5'
      preLoaderRoute: typeof WizardStep5RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-4': {
      id: '/wizard/step-4'
      path: '/step-4'
      fullPath: '/wizard/step-4'
      preLoaderRoute: typeof WizardStep4RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-3': {
      id: '/wizard/step-3'
      path: '/step-3'
      fullPath: '/wizard/step-3'
      preLoaderRoute: typeof WizardStep3RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-2': {
      id: '/wizard/step-2'
      path: '/step-2'
      fullPath: '/wizard/step-2'
      preLoaderRoute: typeof WizardStep2RouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/step-1': {
      id: '/wizard/step-1'
      path: '/step-1'
      fullPath: '/wizard/step-1'
      preLoaderRoute: typeof WizardStep1RouteImport
      parentRoute: typeof WizardRoute
    }
  }
}

interface WizardRouteChildren {
  WizardStep1Route: typeof WizardStep1Route
  WizardStep2Route: typeof WizardStep2Route
  WizardStep3Route: typeof WizardStep3Route
  WizardStep4Route: typeof WizardStep4Route
  WizardStep5Route: typeof WizardStep5Route
  WizardStep6Route: typeof WizardStep6Route
  WizardStep7Route: typeof WizardStep7Route
}

const WizardRouteChildren: WizardRouteChildren = {
  WizardStep1Route: WizardStep1Route,
  WizardStep2Route: WizardStep2Route,
  WizardStep3Route: WizardStep3Route,
  WizardStep4Route: WizardStep4Route,
  WizardStep5Route: WizardStep5Route,
  WizardStep6Route: WizardStep6Route,
  WizardStep7Route: WizardStep7Route,
}

const WizardRouteWithChildren =
  WizardRoute._addFileChildren(WizardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AutopilotRoute: AutopilotRoute,
  MarketGapsRoute: MarketGapsRoute,
  ReportRoute: ReportRoute,
  StartupsRoute: StartupsRoute,
  WizardRoute: WizardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
